/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bloodbank;

import static bloodbank.Login.loginby;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Aashiq
 */
public class StaffRegistation extends javax.swing.JInternalFrame {
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form StaffRegistation
     */
    public StaffRegistation() {
        initComponents();
        conn= DatabaseConnection.db_connect();
        Update_Staff_table();
        AutoStaffNo();
    }
 public void Update_Staff_table(){
        try{
        String sl="select Staff_No,Name,Gender,Phone,Address from Staff";
        pst=conn.prepareStatement(sl);
        rs=pst.executeQuery();
        tbl_staff_list.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(SQLException e){
//        JOptionPane.showMessageDialog(null, e);
        }finally{
            try{
            rs.close();
            pst.close();
            }catch(SQLException e){}
        }
    }
 public void AutoStaffNo(){
        try{
            String sl="select max(Staff_No) from Staff";
            pst=conn.prepareStatement(sl);
            rs=pst.executeQuery();
            String s=rs.getString("max(Staff_No)");
            if(s==null){
            txt_staff_no.setText("1"); 
            }else{
            int a = Integer.parseInt(s);
            int b=a+1;
            txt_staff_no.setText(String.valueOf(b));
            }  
        }catch (NumberFormatException | SQLException e) {
//            JOptionPane.showMessageDialog(null, e);
        }
        finally{
        try{
            rs.close();
            pst.close();
        }catch(SQLException e){}
        }
    }
  public void ClearField(){
    txt_position.setText(null);    
    txt_name.setText(null);
    txt_age.setText(null);
    txt_phone.setText(null);
    txt_email.setText(null);
    txt_address.setText(null);
    txt_search.setText("Enter Staff No,Name,Phone,Address..............");
    cmb_blood_group.setSelectedIndex(0);
    cmb_gender.setSelectedIndex(0);
    Update_Staff_table();
    AutoStaffNo();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_save = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_phone = new javax.swing.JTextField();
        btn_delete = new javax.swing.JButton();
        txt_name = new javax.swing.JTextField();
        cmb_gender = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        cmb_blood_group = new javax.swing.JComboBox<>();
        txt_age = new javax.swing.JTextField();
        txt_position = new javax.swing.JTextField();
        txt_staff_no = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_update = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_address = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_staff_list = new javax.swing.JTable();
        txt_search = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));
        setClosable(true);

        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Position");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Age");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Staff No");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Phone");

        txt_phone.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_phoneActionPerformed(evt);
            }
        });
        txt_phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_phoneKeyTyped(evt);
            }
        });

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        txt_name.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });

        cmb_gender.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmb_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Male", "Female" }));
        cmb_gender.setPreferredSize(new java.awt.Dimension(6, 23));
        cmb_gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_genderActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Blood Group");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Address");

        txt_email.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        cmb_blood_group.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmb_blood_group.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "O+", "O-", "A+", "A-", "B+", "B-", "AB+", "AB-" }));

        txt_age.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txt_position.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txt_staff_no.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_staff_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_staff_noActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Email");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Gender");

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Name");

        txt_address.setColumns(20);
        txt_address.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_address.setRows(5);
        jScrollPane1.setViewportView(txt_address);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel3))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel4)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_save)
                        .addGap(18, 18, 18)
                        .addComponent(btn_update)
                        .addGap(18, 18, 18)
                        .addComponent(btn_delete))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txt_staff_no, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_email)
                        .addComponent(txt_age)
                        .addComponent(txt_phone)
                        .addComponent(jScrollPane1)
                        .addComponent(txt_name)
                        .addComponent(txt_position)
                        .addComponent(cmb_gender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmb_blood_group, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_staff_no, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_position, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_blood_group, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save)
                    .addComponent(btn_update)
                    .addComponent(btn_delete))
                .addContainerGap())
        );

        tbl_staff_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_staff_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_staff_listMouseClicked(evt);
            }
        });
        tbl_staff_list.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbl_staff_listKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_staff_list);

        txt_search.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_search.setText("Enter Staff No,Name,Phone,Address..............");
        txt_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_searchMouseClicked(evt);
            }
        });
        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_searchKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Search");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_phoneActionPerformed

    private void txt_phoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_phoneKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)|| (c==KeyEvent.VK_BACK_SLASH)|| c==KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_txt_phoneKeyTyped

    private void cmb_genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_genderActionPerformed

    private void txt_staff_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_staff_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_staff_noActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        try{            
            String sql1 = "select * from Staff where Staff_No=?";
            pst=conn.prepareStatement(sql1);
            pst.setString(1, txt_staff_no.getText());
            rs=pst.executeQuery();
            if(rs.next()){
            JOptionPane.showMessageDialog(null, "Already Exist");
            }else{
       if("".equals(txt_name.getText())){
            JOptionPane.showMessageDialog(null,"Plese fill up all field");
            txt_name.requestFocus();
        }else if("".equals(txt_age.getText())){
            JOptionPane.showMessageDialog(null,"Plese fill up all field");
            txt_age.requestFocus();
        }else if("".equals(txt_phone.getText())){
            JOptionPane.showMessageDialog(null,"Plese fill up all field");
            txt_phone.requestFocus();
        }else{
                    int p=JOptionPane.showConfirmDialog(null,"Do You Want To Save","Saved",JOptionPane.YES_NO_OPTION);
                    if(p==0){
                        try {
                            String sql = "insert into Staff (Staff_No,Name,Position,Gender,Age,Blood_Group,Phone,Email,Address,Saved_By) values (?,?,?,?,?,?,?,?,?,?)";
                            pst = conn.prepareStatement(sql);
                            pst.setString(1, txt_staff_no.getText());
                            pst.setString(2, txt_name.getText());
                            pst.setString(3, txt_position.getText());
                            pst.setString(4, (cmb_gender.getSelectedItem().toString()));
                            pst.setString(5, txt_age.getText());
                            pst.setString(6, (cmb_blood_group.getSelectedItem().toString()));                            
                            pst.setString(7, txt_phone.getText());
                            pst.setString(8, txt_email.getText());
                            pst.setString(9, txt_address.getText());
                            pst.setString(10, loginby);
                            pst.execute();
                            Update_Staff_table();
                            ClearField();
                            AutoStaffNo();
                            
                            //            JOptionPane.showMessageDialog(null, "Data Saved");
                        }catch (SQLException e) {
                            JOptionPane.showMessageDialog(null, e);
                        }
                        finally{
                            try{
                                rs.close();
                                pst.close();
                            }catch(SQLException e){}
                        }
                    }                   
                }
            }
        }catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }finally{
            try{
                rs.close();
                pst.close();
            }catch(SQLException e){}
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    private void txt_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_searchMouseClicked
        txt_search.setText("");
    }//GEN-LAST:event_txt_searchMouseClicked

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        if("".equals(txt_name.getText())){
            JOptionPane.showMessageDialog(null,"Plese fill up all field");
            txt_name.requestFocus();
        }else if("".equals(txt_age.getText())){
            JOptionPane.showMessageDialog(null,"Plese fill up all field");
            txt_age.requestFocus();
        }else if("".equals(cmb_gender.getSelectedItem().toString())){
            JOptionPane.showMessageDialog(null,"Plese fill up all field");
            cmb_gender.requestFocus();
        }else{
            int p=JOptionPane.showConfirmDialog(null,"Do You Want To Update","Update",JOptionPane.YES_NO_OPTION);
            if(p==0){
                try{
                    String sql = "update Staff set Name='"+txt_name.getText()+"',"
                    + "Position='"+txt_position.getText()+"',"
                    + "Gender='"+cmb_gender.getSelectedItem().toString()+"',"
                    + "Age='"+txt_age.getText()+"',"
                    + "Blood_Group='"+cmb_blood_group.getSelectedItem().toString()+"'," 
                    + "Phone='"+txt_phone.getText()+"',"
                    + "Email='"+txt_email.getText()+"',"
                    + "Address='"+txt_address.getText()+"',"
                    
                    + "Update_By='"+loginby+"'"
                    + "where Staff_No='"+txt_staff_no.getText()+"'";
                    pst = conn.prepareStatement(sql);                   
                    pst.execute();
                    Update_Staff_table();
                    ClearField();
                    AutoStaffNo();
                    //        JOptionPane.showMessageDialog(null,"Upadate");
                }
                catch(SQLException e){
                    JOptionPane.showMessageDialog(null,e);
                }
                finally {
                    try {
                        rs.close();
                        pst.close();
                    }catch (SQLException e) {
                    }
                }
                
            }
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        //--delete blood donor info from database
        if("".equals(txt_name.getText())||"".equals(txt_staff_no.getText())){
        JOptionPane.showMessageDialog(null, "Please Enter Staff No And Name");
        }else{
        int p = JOptionPane.showConfirmDialog(null, "Do You Want To Delete", "Delete", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            try {
                String sql = "delete from Staff where Staff_No=? and Name=?";
                pst = conn.prepareStatement(sql);
                pst.setString(1, txt_staff_no.getText());
                pst.setString(2, txt_name.getText());
                pst.execute();
                
                AutoStaffNo();
                ClearField();
                Update_Staff_table();
//                JOptionPane.showMessageDialog(null, "Data Deleted");

            } catch (Exception e) {
//                JOptionPane.showMessageDialog(null, e);
            } finally {
                try {
                    rs.close();
                    pst.close();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        }
        
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void tbl_staff_listKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_staff_listKeyReleased
        //----table up down key and set value text field
        try{
            int row=tbl_staff_list.getSelectedRow();
            String tableClick=(tbl_staff_list.getModel().getValueAt(row, 0).toString());
            String sql="select * from Staff where Staff_No='"+tableClick+"' ";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                txt_staff_no.setText(rs.getString("Staff_No"));
                txt_name.setText(rs.getString("Name"));
                txt_position.setText(rs.getString("Position"));
                txt_age.setText(rs.getString("Age"));
                txt_phone.setText(rs.getString("Phone"));
                txt_email.setText(rs.getString("Email"));
                txt_address.setText(rs.getString("Address"));
                cmb_blood_group.setSelectedItem(rs.getString("Blood_Group"));
                cmb_gender.setSelectedItem(rs.getString("Gender"));
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }finally{
            try{
                rs.close();
                pst.close();
            }catch(SQLException e){}
        }
    }//GEN-LAST:event_tbl_staff_listKeyReleased

    private void tbl_staff_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_staff_listMouseClicked
            try{
            int row=tbl_staff_list.getSelectedRow();
            String tableClick=(tbl_staff_list.getModel().getValueAt(row, 0).toString());
            String sql="select * from Staff where Staff_No='"+tableClick+"' ";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                txt_staff_no.setText(rs.getString("Staff_No"));
                txt_name.setText(rs.getString("Name"));
                txt_position.setText(rs.getString("Position"));
                txt_age.setText(rs.getString("Age"));
                txt_phone.setText(rs.getString("Phone"));
                txt_email.setText(rs.getString("Email"));
                txt_address.setText(rs.getString("Address"));
                cmb_blood_group.setSelectedItem(rs.getString("Blood_Group"));
                cmb_gender.setSelectedItem(rs.getString("Gender"));
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }finally{
            try{
                rs.close();
                pst.close();
            }catch(SQLException e){}
        }
    }//GEN-LAST:event_tbl_staff_listMouseClicked

    private void txt_searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyPressed
         //----search press any key then result set jtable
        try {
            String sql1 = "select Staff_No,Name,Gender,Phone,Address from Staff  where Blood_Group || Name || Staff_No || Phone || Address like  '%" + txt_search.getText() + "%' order by Donor_No asc";
            pst=conn.prepareStatement(sql1);
            rs=pst.executeQuery();
            tbl_staff_list.setModel(DbUtils.resultSetToTableModel(rs));
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null,e);
        }finally {
            try {
                rs.close();
                pst.close();
            }catch (SQLException e) {}
        }
    }//GEN-LAST:event_txt_searchKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cmb_blood_group;
    private javax.swing.JComboBox<String> cmb_gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_staff_list;
    private javax.swing.JTextArea txt_address;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_position;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_staff_no;
    // End of variables declaration//GEN-END:variables
}
